DROP TABLE IF EXISTS PrintDetail;
DROP TABLE IF EXISTS PhotoPrint;
DROP TABLE IF EXISTS FilmDevelopment;
DROP TABLE IF EXISTS `Order`;
DROP TABLE IF EXISTS ServiceOrder;
DROP TABLE IF EXISTS ServiceType;
DROP TABLE IF EXISTS Sale;
DROP TABLE IF EXISTS Distribution;
DROP TABLE IF EXISTS Supply;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS SupplierSpecialization;
DROP TABLE IF EXISTS Supplier;
DROP TABLE IF EXISTS ProfiDiscount;
DROP TABLE IF EXISTS DiscountCard;
DROP TABLE IF EXISTS `Client`;
DROP TABLE IF EXISTS UserRole;
DROP TABLE IF EXISTS Employee; 
DROP TABLE IF EXISTS Workplace;
DROP TABLE IF EXISTS Kiosk;
DROP TABLE IF EXISTS Branch;
DROP TABLE IF EXISTS MainOffice;
DROP TABLE IF EXISTS ProductCategory; 
DROP TABLE IF EXISTS RolePermission;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Permission;





